export const LOGIN_URL = "/login"
export const SESSION_TOKEN = "_session_token"
export const REFRESH_TOKEN = "_refresh_token"
export const TASK_GROUP = "_selected_group"
export const USER_DATA = "_user_data"

// export const BASE_URL = "https://vpn101-3000.forgeforce.org/"
export const BASE_URL = "https://meetoo.digicx.id:8443/"
export const STOMP_URL = BASE_URL + "ws"
export const API_URL = BASE_URL + "api/v1/"
export const WEB_RTC = BASE_URL + "rtc/"